### ISSUE TITLE
Leaphy Oled

### ISSUE THREAD

**Issue by beekumo** [leaphy-robotics/leaphy-blockly#213]
[Log display 6mei22.txt](https://github.com/leaphy-robotics/leaphy-blockly/files/8638525/Log.display.6mei22.txt)
Leaphy Oled does not display text

When writing text in the display rg 1 block in Leaphy extra the Oled screen does not display the text that was written. It keeps displaying 'Leaphy Oled'. Tried various ways to solve this, used 2 different Uno's and 2 different Oled displays, problem does not seem to be a hardware issue. 

Have added the datalog, hopefully this issues can be solved easily :-)

**Comment by ghost** [comment]
Hi @beekumo, 
This is due to how the OLED blocks have been set up. To enable writing to different rows in the OLED screen, we went for a solution where you have to set the rows and then manually trigger it to display them, like this:

![image](https://user-images.githubusercontent.com/58653521/167258205-5ff63076-1775-43b1-af83-d9c7ddefe694.png)

This should solve your problem. Feel free to reopen this issue if there are still problems.
